Implement homework 3
Logen9/Android_academy_app pull request #2
Opened 2020-11-22 21:43 UTC by Logen9

v1 with strange behavior on rating icons

2020-11-26 07:41 UTC, industradamus requested changes
- Ты видимо не совсем правильно понял концепцию ConstrainLayout. Макет не должен весь верстаться отступами от верхней части экрана. Обычно ты ставишь какой-то верхний элемент и от него дальше вниз ставишь другие. Т.е. view должны быть размещены относительно друг друга и границ родителя, а у тебя все размещены относительно родителя и никак не учитывают существование других View. Если делать разметку так как сделал ты - то при любом изменении размеров View, твой макет пойдет по одному месту. Все View начнут налазить друг на друга. 
- Цвета нужно выносить в ресурсы. 
- Убери везде жесткие размеры TextView. Вряд-ли ты хочешь чтоб везде был 1 четкий размер? А что если у тебя будет длинный текст или на 2 строки?

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/Movie_button"
id - шники даются либо через нижний слеш маленькими буквами, либо camelCase, но первая буква маленькая

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +        tools:layout_editor_absoluteX="171dp"
Зачем эти 2 строки тут?
```
tools:layout_editor_absoluteX="171dp"
tools:layout_editor_absoluteY="132dp"
```

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +
Лишние пустые строки. Это важно, на это смотрят на тестовых заданиях на работу и собственно на самой работе. Это как личная гигиена, код должен быть чистым и там не должно быть ничего лишнего

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +    android:background="#191926"
Цвета стоит выносить в ресурсы

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
А какую смысловую нагрузку несет ConstraintLayout если внутри него все обернуто в ScrollView. Так ты увеличиваешь время отрисовки. Сделай просто корневым лейаутом свой ScrollView и все

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:background="#191926"
В ресурсы

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +                app:layout_constraintHorizontal_bias="0.0"
Я думаю это тут не нужно

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +            android:background="#191926"
И все остальные цвета

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +                android:letterSpacing="-0.01"
Это в дизайне так? Такой спейсинг реально на что-то влияет?

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +            <androidx.constraintlayout.widget.Guideline
Убери его и просто поставь в корневом лейауте паддинги start и end по 16dp.

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +                app:layout_constraintHorizontal_bias="0.0"
Мне кажется это тоже лишнее

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +                android:layout_width="78dp"
А что будет если пользователь в настройках поменяет размер шрифта на "Крупный"? Или на мелкий? Для TextView не задаются так размеры. Если тебе нужно, чтоб TextView была не больше определенного размера - ты можешь задать ей ширину к примеру, но тогда надо обработать кейсы когда текст не влезет. А тебе достаточно сделать wrap_content. Не надо такие размеры тупо копировать из фигмы. Там они по дефолту высчитываются от размера текста, в реале ты не хочешь обычно так жестко задавать размер. (бывают исключения, но на практике я такого не делал ни разу). 

Когда тебе дают дизайн - ты должен понимать, что конкретно от тебя хотят. К примеру:
- чтоб текст всегда занимал 1 строку и был не больше чем на пол экрана - тогда ты ставишь maxLine=1 и задаешь какой-то барьер или хардкоженый размер.
- тебе достаточно чтоб он имел отступы от краев 16dp - тогда задаешь только отступы от краев.

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +                app:layout_constraintTop_toTopOf="parent" />
Не надо все View задавать от верха экрана и задавать потом такие хардкоженные отступы. Тебе макет верстать надо сверху и дальше каждый элементы под предыдущим. И регулировать отступы не от верха, а от верхнего элемента. Вряд-ли когда дизайнер рисовал этот макет он считал, что должен быть отступ 362 dp от верху, вероятно он делал 4pd от надписи с жанром. 

В твоем кейсе если надпись жанр увеличится или будет занимать 2 строки view налезут друг на друга

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +                android:layout_marginStart="103dp"
По рекомендациям материал дизайна все размеры должны быть кратны 2. Если видишь в дизайне не такой отступ - можно пинать дизайнера, они обычно соглашаются (если это конеш адекватные дизайнеры)

2020-11-26 07:41 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details.xml
> +                android:layout_marginStart="103dp"
А второй кейс, в том, что это не должно задаваться от края. А отступ должен быть от звездочек. Что если звездочек станет 6? Тебе придется руками править этот отступ.

2020-12-01 19:10 UTC, Logen9 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/Movie_button"
Исправил, залил второй коммит

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +        tools:layout_editor_absoluteX="171dp"
Исправил

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +
Исправил

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +    android:background="#191926"
Исправил

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Исправил

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +            <androidx.constraintlayout.widget.Guideline
Исправил

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +                app:layout_constraintHorizontal_bias="0.0"
Исправил

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +                app:layout_constraintTop_toTopOf="parent" />
Исправил

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +                android:layout_width="78dp"
Исправил

2020-12-01 19:11 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details.xml
> +                android:layout_marginStart="103dp"
Исправил

2020-12-01 19:34 UTC, industradamus commented on app/src/main/java/ru/sparrow/android_app/MainActivity.kt
> +        textView.setOnClickListener {moveToScreen()}
`findViewById<TextView>(R.id.movie_button).setOnClickListener {moveToScreen()}` - раз уж не хочешь синтетики. Типа для чего тут создавать переменную если она только в 1 месте используется

2020-12-01 19:34 UTC, industradamus commented on app/src/main/java/ru/sparrow/android_app/MainActivity.kt
Убери  пустые строки. Да и интент тут оч простой, можно в целом не создавать отдельную переменную, а прям в методе:
`startActivity(Intent(this, MovieDetailsActivity::class.java))`

2020-12-01 19:34 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details_scroll.xml
> +            android:id="@+id/Actor_name_3"
Раз у тебя так много общего в каждом TextView почему бы не вынести в один стиль?

2020-12-01 19:34 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details_scroll.xml
> +            android:id="@+id/rating_icon5"
Подтянул бы уже либу для рейтинг бара. А то потом вы ж будете их задавать динамически, и руками задавать 5 звезд это будет как-то стремно.

2020-12-06 18:40 UTC, Logen9 commented on app/src/main/java/ru/sparrow/android_app/MainActivity.kt
Готово

2020-12-06 18:40 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details_scroll.xml
> +            android:id="@+id/Actor_name_3"
Готово

2020-12-06 18:41 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details_scroll.xml
> +            android:id="@+id/rating_icon5"
Готово, притащил стандартную либу

2020-12-08 19:29 UTC, industradamus commented on app/src/main/java/ru/sparrow/android_app/MainActivity.kt
> +    private fun moveToScreen(){
Название функции ни о чем не говорит. Условно если бы тут было что-то вроде `moveToScreen(screen: Activity)` - то это было бы логично, но в твоем кейсе это открытие экрана. Так что стоит обозвать что-то вроде `moveToDetails()`. Ну и в целом тут 1 строка причем достаточно короткая и понятная. Стоит ли ее вообще выносить?

2020-12-08 19:29 UTC, industradamus commented on app/src/main/res/layout/activity_movie_details_scroll.xml
> +            android:layout_width="80dp"
Раз уж не используешь либу (а я рекомендую не париться и подтянуть либу, потому как потом будешь трахаться с тем чтоб это все жмакалось) то сделай хоть стиль для них один. чтоб код каждой звезды занимал 3-5 строчек

2020-12-08 19:47 UTC, Logen9 commented on app/src/main/res/layout/activity_movie_details_scroll.xml
> +            android:layout_width="80dp"
Подтянуть либу - в смысле запихнуть в RecyclerView?

2020-12-08 20:27 UTC, Logen9 commented on app/src/main/java/ru/sparrow/android_app/MainActivity.kt
> +    private fun moveToScreen(){
В рамках этого домашнего задания я вынес из-за дизайна (висело callback'ом на кнопке), в следующем уже будет сделано как требует новое дз

2020-12-08 20:43 UTC, merged